### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /app/node_modules/uuid/package.json

### ISSUE THREAD

**Issue by bjohnson-ionrev** [doronnahum/feathers-mongoose-casl#25]
lib/src/utils/uploadMiddleware/utils/handleUpload.js

current:
`const uuidv4 = require('uuid/v4');`

change to:
`const { v4: uuidv4 } = require('uuid');`

`server_1  | > nodemon src/
server_1  | [nodemon] 1.19.4
server_1  | [nodemon] to restart at any time, enter `rs`
server_1  | [nodemon] watching dir(s): *.*
server_1  | [nodemon] watching extensions: js,mjs,json
server_1  | [nodemon] starting `node src/`
server_1  | internal/modules/cjs/loader.js:491
server_1  |   throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
server_1  |   ^
server_1  | Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /app/node_modules/uuid/package.json
server_1  |     at applyExports (internal/modules/cjs/loader.js:491:9)
server_1  |     at resolveExports (internal/modules/cjs/loader.js:507:23)
server_1  |     at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
server_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
server_1  |     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
server_1  |     at Module.require (internal/modules/cjs/loader.js:1026:19)
server_1  |     at require (internal/modules/cjs/helpers.js:72:18)
server_1  |     at Object.<anonymous> (/app/node_modules/feathers-mongoose-casl/lib/src/utils/uploadMiddleware/utils/handleUpload.js:2:16)
server_1  |     at Module._compile (internal/modules/cjs/loader.js:1138:30)
server_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
server_1  |   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
server_1  | }
server_1  | [nodemon] app crashed - waiting for file changes before starting...
`

See ... https://github.com/uuidjs/uuid#deep-requires-now-deprecated

here's the notes ...
Deep Requires Now Deprecated
uuid@3 encouraged the use of deep requires to minimize the bundle size of browser builds:

const uuidv4 = require('uuid/v4'); // <== NOW DEPRECATED!
uuidv4();
As of uuid@7 this library now provides ECMAScript modules builds, which allow packagers like Webpack and Rollup to do "tree-shaking" to remove dead code. Instead, use the import syntax:

import { v4 as uuidv4 } from 'uuid';
uuidv4();
... or for CommonJS:

const { v4: uuidv4 } = require('uuid');
uuidv4();

**Comment by doronnahum** [comment]
thanks @bjohnson-ionrev
